version: '3'

services:
  nginx:
    image: nginx:1.25
    ports:
      - 80:80
    depends_on:
      - dj
    volumes:
      - static:/www/static:ro
      - nginx-config:/etc/nginx/conf.d:ro
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - 5432:5432
  dj:
    image: hook-test:1
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - static:/static
      - nginx-config:/configs/nginx

volumes:
  static:
  nginx-config: